spring.application.name=backend

spring.datasource.url=jdbc:h2:mem:regula
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.data-locations=classpath:schema.sql,classpath:data.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

#H2 database (in-memory)

# JWT configuration
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION}
